services:
  - type: web
    name: face-detection-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --max-requests 100 --max-requests-jitter 10 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
